exclude: ".*/data/.*"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: '.*\.svg'
      - id: end-of-file-fixer
        exclude: '.*\.svg'
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
      - id: ruff
        args: [ --select, ISC001, --fix ]
