version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - gfortran
    - graphviz
    - libblas-dev
    - liblapack-dev
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
