"""
PyAFQ tractometry and visualization
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

.. autofunction:: init_pyafq_wf

"""
import nipype.pipeline.engine as pe
import nipype.interfaces.utility as niu
import logging
from qsiprep.interfaces.pyafq import PyAFQRecon
from .interchange import recon_workflow_input_fields
from ...interfaces.bids import ReconDerivativesDataSink
LOGGER = logging.getLogger('nipype.workflow')


# TODO: look at desc from mrtrix workflow.__desc__ = desc

def init_pyafq_wf(omp_nthreads, available_anatomical_data,
                  name="afq", output_suffix="", params={}):
    """Run PyAFQ on some qsiprep outputs

    Inputs

        *qsiprep outputs*

    Outputs
        profiles_csv
            CSV file containing the tract profiles generated by pyAFQ.

    """
    inputnode = pe.Node(niu.IdentityInterface(
        fields=recon_workflow_input_fields + ['tck_file']),
        name="inputnode")
    outputnode = pe.Node(
        niu.IdentityInterface(fields=['afq_dir']),
        name="outputnode")

    params["omp_nthreads"] = omp_nthreads
    run_afq = pe.Node(PyAFQRecon(kwargs=params), name='run_afq')
    workflow = pe.Workflow(name=name)
    if params.get("use_external_tracking", False):
        workflow.connect([
            (inputnode, run_afq, [('tck_file', 'tck_file')]),
        ])
    workflow.connect([
        (inputnode, run_afq, [
            ('dwi_file', 'dwi_file'),
            ('bval_file', 'bval_file'),
            ('bvec_file', 'bvec_file'),
            ('dwi_mask', 'mask_file'),
            ('t1_2_mni_reverse_transform', 'itk_file')]),
        (run_afq, outputnode, [('afq_dir', 'afq_dir')])
    ])
    if output_suffix:
        # Save the output in the outputs directory
        ds_afq = pe.Node(
            ReconDerivativesDataSink(),
            name='ds_' + name,
            run_without_submitting=True)
        workflow.connect(run_afq, 'afq_dir', ds_afq, 'in_file')
    return workflow
