"""Value objects describing how a subject's DWI scans are grouped.

Everything in this module is expressed in BIDS vocabulary:

- :class:`FieldmapEstimation` corresponds to a ``B0FieldIdentifier``: the set
  of files that are combined to estimate one fieldmap.
- The application mapping in :class:`DWIGrouping` corresponds to
  ``B0FieldSource``: which estimation corrects which DWI file.
- :class:`ConcatenationGroup` corresponds to a ``MultipartID``: which DWI
  files are concatenated in the output derivatives.
- :class:`DistortionGroup` is derived (never curated): the files that share
  one susceptibility warp *and* one correction.

When the user has curated these fields in their sidecars the values are used
verbatim; otherwise equivalent values are inferred and tagged with their
:class:`Provenance`. Inferred identifiers always start with the reserved
``auto+`` prefix, so they can never collide with curated values.

Nothing in this module knows how eddy, TOPUP, or DRBUDDI want their inputs
arranged - that knowledge belongs to adapters and reports that consume a
:class:`DWIGrouping`.
"""

from __future__ import annotations

import dataclasses
import enum
import os.path as op
from collections import defaultdict
from collections.abc import Mapping
from types import MappingProxyType
from typing import Any

import numpy as np

#: Reserved prefix for identifiers generated by qsiprep. ``+`` cannot appear
#: in a BIDS filename entity and is not expected in curated identifiers, so a
#: curated value starting with this prefix is treated as an error.
AUTO_PREFIX = 'auto+'

#: Seconds; TotalReadoutTime values closer than this are considered equal.
READOUT_TOLERANCE = 1e-4


class Provenance(enum.StrEnum):
    """Where a grouping decision came from."""

    CURATED = 'curated'  # explicit B0FieldIdentifier/B0FieldSource/MultipartID
    TRANSLATED = 'intendedfor'  # translated from IntendedFor
    FORCED = 'cli-override'  # requested by a command-line flag
    INFERRED = 'inferred'  # heuristic

    def tag(self):
        """Short bracketed tag for report text."""
        return f'[{self.value}]'


class EstimationMethod(enum.StrEnum):
    """How a fieldmap is estimated from its source files."""

    PEPOLAR = 'pepolar'  # EPI images with differing phase encoding
    DIRECT = 'fieldmap'  # precomputed fieldmap + magnitude
    PHASEDIFF = 'phasediff'  # phase difference + magnitude(s)
    PHASES = 'two_phases'  # phase1 + phase2 + magnitude(s)
    SYNB0 = 'synb0'  # fieldmap-less: synthetic undistorted b=0 from the T1w
    ANAT_CONTRAST = 'anat_reg'  # fieldmap-less: b=0 registration to a T2w (T2Wreg)
    SYN = 'syn'  # fieldmap-less: ANTs SyN registration to a template (classic)


@dataclasses.dataclass(frozen=True)
class DistortionSignature:
    """The acquisition parameters that determine a susceptibility warp.

    Two EPI images acquired with the same signature are distorted the same
    way. ``parallel_factor`` and ``multiband_factor`` are informational and
    do not participate in equality: they are already reflected in
    ``readout_time`` when it is reported correctly.
    """

    pe_dir: str | None = None  # PhaseEncodingDirection, e.g. 'j-'
    readout_time: float | None = None  # TotalReadoutTime, seconds
    shim: tuple | None = None  # tuple(ShimSetting) when present
    parallel_factor: float | None = dataclasses.field(default=None, compare=False)
    multiband_factor: int | None = dataclasses.field(default=None, compare=False)

    @property
    def pe_axis(self) -> str | None:
        """The phase encoding axis: 'i', 'j', or 'k'."""
        return self.pe_dir[0] if self.pe_dir else None

    @property
    def pe_polarity(self) -> int | None:
        """+1 or -1 along ``pe_axis``."""
        if not self.pe_dir:
            return None
        return -1 if self.pe_dir.endswith('-') else 1

    @property
    def key(self) -> tuple:
        """Hashable identity used to partition files into distortion groups."""
        return (self.pe_dir, self.readout_time, self.shim)

    def compatible_shim(self, other: DistortionSignature, ignore_shims: bool = False) -> bool:
        """True if the two shims are equal, either is unknown, or shims are ignored."""
        if ignore_shims or self.shim is None or other.shim is None:
            return True
        return self.shim == other.shim

    def describe(self) -> str:
        """One-line human-readable summary."""
        parts = []
        parts.append(f'PE {self.pe_dir}' if self.pe_dir else 'PE unknown')
        if self.readout_time is not None:
            parts.append(f'TRT {self.readout_time:g}s')
        if self.shim is not None:
            parts.append('shimmed')
        return ', '.join(parts)


@dataclasses.dataclass(frozen=True)
class GridInfo:
    """The sampling grid of a NIfTI image: shape, voxel size, and affine.

    Comparison tolerances are deliberate heuristics: scanner float jitter
    between runs of an unchanged protocol stays well below all of them.
    """

    shape: tuple[int, int, int]
    zooms: tuple[float, float, float]
    affine: tuple  # 4 rows of 4 floats

    #: mm; origin differences at or below this are "the same field of view".
    TRANSLATION_TOL = 0.05
    #: unitless; max element difference between normalized direction cosines.
    ROTATION_TOL = 1e-3
    #: mm; voxel size differences above this are different grids.
    ZOOM_TOL = 0.01

    def _directions(self) -> np.ndarray:
        rotation = np.asarray(self.affine, dtype=float)[:3, :3]
        norms = np.linalg.norm(rotation, axis=0)
        norms[norms == 0] = 1.0
        return rotation / norms

    def _origin(self) -> np.ndarray:
        return np.asarray(self.affine, dtype=float)[:3, 3]

    def shift_mm(self, other: GridInfo) -> float:
        """Distance between the two grid origins."""
        return float(np.linalg.norm(self._origin() - other._origin()))

    def rotation_deg(self, other: GridInfo) -> float:
        """Angle of the rotation relating the two grid orientations."""
        rotation = self._directions().T @ other._directions()
        cos_angle = np.clip((np.trace(rotation) - 1.0) / 2.0, -1.0, 1.0)
        return float(np.degrees(np.arccos(cos_angle)))

    def compare(self, other: GridInfo) -> str:
        """Classify how two grids relate.

        Returns one of:

        - ``'match'``: same grid; the series can be stacked directly.
        - ``'shifted'``: same shape/spacing/orientation, origins differ - a
          rigid field-of-view offset. Affines can be overwritten to align,
          but the FoV move may have triggered a scanner re-shim.
        - ``'oblique'``: orientations (direction cosines) differ - slice axes
          are not parallel, so axis-aligned distortion corrections cannot be
          applied correctly to a naive concatenation.
        - ``'grid'``: different matrix size or voxel size - volumewise
          stacking is impossible without resampling.
        """
        if self.shape != other.shape or not np.allclose(
            self.zooms, other.zooms, atol=self.ZOOM_TOL
        ):
            return 'grid'
        if not np.allclose(self._directions(), other._directions(), atol=self.ROTATION_TOL):
            return 'oblique'
        if self.shift_mm(other) > self.TRANSLATION_TOL:
            return 'shifted'
        return 'match'


@dataclasses.dataclass(frozen=True, eq=False)
class FileRecord:
    """One NIfTI file in ``dwi/`` or ``fmap/`` plus its grouping metadata.

    All sidecar metadata relevant to grouping is read exactly once, into this
    record (see :func:`qsiprep.grouping.metadata.index_subject`). ``eq=False``
    keeps identity semantics: records are always referenced by ``path``.
    """

    path: str  # absolute path
    datatype: str  # 'dwi' | 'fmap' | 'anat'
    suffix: str  # dwi|epi|fieldmap|phasediff|phase1|phase2|magnitude*|sbref|T1w|T2w
    session: str | None
    signature: DistortionSignature
    # Curated fields, verbatim (empty/None when absent):
    b0field_identifiers: tuple[str, ...] = ()
    b0field_sources: tuple[str, ...] = ()
    multipart_id: str | None = None
    intended_for: tuple[str, ...] = ()  # resolved absolute paths (fmap only)
    metadata: Mapping[str, Any] = dataclasses.field(default_factory=dict)
    # Read from the sibling .bval file (dwi only); None = undetermined:
    shelled: bool | None = None
    shells: tuple[float, ...] = ()  # shell centre b-values, for reporting
    max_bval: float | None = None
    # Read from the NIfTI header (dwi only); None = unreadable/undetermined:
    grid: GridInfo | None = None

    def __post_init__(self):
        # Freeze the raw sidecar so nothing downstream can mutate shared state.
        if not isinstance(self.metadata, MappingProxyType):
            object.__setattr__(self, 'metadata', MappingProxyType(dict(self.metadata)))

    @property
    def filename(self) -> str:
        return op.basename(self.path)

    @property
    def is_dwi(self) -> bool:
        return self.datatype == 'dwi'

    @property
    def is_anat(self) -> bool:
        return self.datatype == 'anat'

    @property
    def is_epi_like(self) -> bool:
        """True if this file can serve as a PEPOLAR (blip-up/blip-down) source."""
        return self.suffix in ('dwi', 'epi', 'sbref')


@dataclasses.dataclass(frozen=True)
class FieldmapEstimation:
    """A set of files that jointly estimate one fieldmap (one B0FieldIdentifier)."""

    b0field_id: str
    method: EstimationMethod
    sources: tuple[str, ...]  # file paths, sorted
    provenance: Provenance
    # Derived from EPI-like sources (empty for GRE methods):
    pe_axes: frozenset[str] = frozenset()
    bidirectional_axes: frozenset[str] = frozenset()

    @property
    def is_pepolar(self) -> bool:
        return self.method is EstimationMethod.PEPOLAR


@dataclasses.dataclass(frozen=True)
class DistortionGroup:
    """DWI files sharing one susceptibility warp and one correction.

    Derived, never curated: the partition key is
    ``(signature.key, applied estimation, concatenation membership)``, so a
    distortion group can never span two fieldmaps or two output files.
    """

    key: str  # stable human-readable id, e.g. 'ses-1_acq-98dir_dir-AP'
    signature: DistortionSignature
    dwi_files: tuple[str, ...]  # sorted
    b0field_source: str | None  # estimation id that corrects this group


@dataclasses.dataclass(frozen=True)
class ConcatenationGroup:
    """DWI files concatenated into one output (one MultipartID)."""

    multipart_id: str  # curated MultipartID or 'auto+...'
    provenance: Provenance
    distortion_groups: tuple[str, ...]  # DistortionGroup keys, sorted
    dwi_files: tuple[str, ...]  # union of members, sorted
    output_name: str  # e.g. 'sub-1_ses-1' - the concatenated BIDS name


@dataclasses.dataclass
class DWIGrouping:
    """The complete grouping decision for one subject.

    ``application`` maps each DWI file to the ``b0field_id`` of the estimation
    that corrects it (its effective ``B0FieldSource``), or ``None`` when no
    correction source exists. ``application_candidates`` retains every
    estimation that *could* have corrected the file, so reports can show what
    lost and why.
    """

    subject_id: str
    files: dict[str, FileRecord]  # path -> record (dwi and fmap)
    estimations: dict[str, FieldmapEstimation]  # b0field_id -> estimation
    application: dict[str, str | None]  # dwi path -> b0field_id or None
    application_provenance: dict[str, Provenance]
    application_candidates: dict[str, tuple[str, ...]]  # dwi path -> all candidate ids
    distortion_groups: dict[str, DistortionGroup]
    concatenation_groups: dict[str, ConcatenationGroup]
    issues: list = dataclasses.field(default_factory=list)
    #: SyNb0 was requested: a synthetic undistorted b=0 is available as the
    #: structural target for registration-based stages, overriding any T2w.
    synb0_requested: bool = False

    @property
    def dwi_files(self) -> list[str]:
        return sorted(path for path, rec in self.files.items() if rec.is_dwi)

    def anat_files(self, suffix: str) -> list[str]:
        """This subject's indexed anatomical images with the given suffix."""
        return sorted(
            path for path, rec in self.files.items() if rec.is_anat and rec.suffix == suffix
        )

    @property
    def errors(self) -> list:
        return [issue for issue in self.issues if issue.severity == 'error']

    @property
    def warnings(self) -> list:
        return [issue for issue in self.issues if issue.severity == 'warning']

    def distortion_groups_in(self, multipart_id: str) -> list[DistortionGroup]:
        """The member distortion groups of a concatenation group."""
        concat = self.concatenation_groups[multipart_id]
        return [self.distortion_groups[key] for key in concat.distortion_groups]

    def borrowed_sources(self, multipart_id: str) -> dict[str, list[str]]:
        """DWI series used by this concatenation group's fieldmap estimation
        that are not members of the group (the "borrowing" case).

        fmap/ sources are not "borrowed" - being outside the outputs is their
        normal role. Returns a mapping of estimation id -> sorted list of
        borrowed DWI paths.
        """
        concat = self.concatenation_groups[multipart_id]
        members = set(concat.dwi_files)
        borrowed = {}
        for dgroup in self.distortion_groups_in(multipart_id):
            if dgroup.b0field_source is None:
                continue
            estimation = self.estimations[dgroup.b0field_source]
            outside = sorted(
                path
                for path in set(estimation.sources) - members
                if path in self.files and self.files[path].is_dwi
            )
            if outside:
                borrowed[estimation.b0field_id] = outside
        return borrowed

    def to_dict(self) -> dict:
        """JSON-serializable rendering of the full grouping."""
        return {
            'subject_id': self.subject_id,
            'files': {
                path: {
                    'datatype': rec.datatype,
                    'suffix': rec.suffix,
                    'session': rec.session,
                    'pe_dir': rec.signature.pe_dir,
                    'readout_time': rec.signature.readout_time,
                    'shim': list(rec.signature.shim) if rec.signature.shim else None,
                    'b0field_identifiers': list(rec.b0field_identifiers),
                    'b0field_sources': list(rec.b0field_sources),
                    'multipart_id': rec.multipart_id,
                    'intended_for': list(rec.intended_for),
                    'shelled': rec.shelled,
                    'shells': list(rec.shells),
                    'max_bval': rec.max_bval,
                    'grid': (
                        {'shape': list(rec.grid.shape), 'zooms': list(rec.grid.zooms)}
                        if rec.grid
                        else None
                    ),
                }
                for path, rec in sorted(self.files.items())
            },
            'estimations': {
                b0field_id: {
                    'method': est.method.value,
                    'sources': list(est.sources),
                    'provenance': est.provenance.value,
                    'pe_axes': sorted(est.pe_axes),
                    'bidirectional_axes': sorted(est.bidirectional_axes),
                }
                for b0field_id, est in sorted(self.estimations.items())
            },
            'application': dict(sorted(self.application.items())),
            'application_provenance': {
                path: prov.value for path, prov in sorted(self.application_provenance.items())
            },
            'distortion_groups': {
                key: {
                    'pe_dir': group.signature.pe_dir,
                    'readout_time': group.signature.readout_time,
                    'shim': list(group.signature.shim) if group.signature.shim else None,
                    'dwi_files': list(group.dwi_files),
                    'b0field_source': group.b0field_source,
                }
                for key, group in sorted(self.distortion_groups.items())
            },
            'concatenation_groups': {
                multipart_id: {
                    'provenance': group.provenance.value,
                    'distortion_groups': list(group.distortion_groups),
                    'dwi_files': list(group.dwi_files),
                    'output_name': group.output_name,
                }
                for multipart_id, group in sorted(self.concatenation_groups.items())
            },
            'issues': [
                {
                    'severity': issue.severity,
                    'code': issue.code,
                    'message': issue.message,
                    'files': list(issue.files),
                }
                for issue in self.issues
            ],
        }


def strip_nii_ext(filename: str) -> str:
    """Basename of a NIfTI path without its ``.nii``/``.nii.gz`` extension."""
    basename = op.basename(filename)
    for ext in ('.nii.gz', '.nii'):
        if basename.endswith(ext):
            return basename[: -len(ext)]
    return op.splitext(basename)[0]


def derive_output_name(paths) -> str:
    """Derive the BIDS name for the concatenation of ``paths``.

    The single implementation of what used to exist twice (in
    ``qsiprep.utils.grouping.get_concatenated_bids_name`` and
    ``qsiprep.workflows.dwi.util._get_concatenated_bids_name``): keep the
    entities from the whitelist that all files share.

    Examples
    --------
    >>> derive_output_name([
    ...     '/data/sub-1/dwi/sub-1_dir-AP_run-1_dwi.nii.gz',
    ...     '/data/sub-1/dwi/sub-1_dir-AP_run-2_dwi.nii.gz',
    ... ])
    'sub-1_dir-AP'
    >>> derive_output_name([
    ...     '/data/sub-1/dwi/sub-1_dir-AP_dwi.nii.gz',
    ...     '/data/sub-1/dwi/sub-1_dir-PA_dwi.nii.gz',
    ... ])
    'sub-1'
    >>> derive_output_name(['/data/sub-1/dwi/sub-1_dir-AP_dwi.nii.gz'])
    'sub-1_dir-AP'
    """
    paths = sorted(paths)
    if len(paths) == 1:
        fname = strip_nii_ext(paths[0])
    else:
        bids_keys = defaultdict(set)
        for path in paths:
            for token in strip_nii_ext(path).split('_'):
                parts = token.split('-', 1)
                if len(parts) == 2:
                    bids_keys[parts[0]].add(parts[1])
        common = [
            f'{key}-{next(iter(bids_keys[key]))}'
            for key in ('sub', 'ses', 'acq', 'dir', 'run')
            if len(bids_keys[key]) == 1
        ]
        fname = '_'.join(common)

    if fname.endswith('_dwi'):
        fname = fname[:-4]
    return fname.replace('.', '').replace(' ', '')
