"""Simulated test fixtures generated with TRXScan.

Each entry of :data:`RECIPES` is one ``trxscan-fixture`` invocation (a recipe name and its
``--set`` parameters). The fixtures are BIDS datasets with their ground truth under
``derivatives/trxscan`` (see :mod:`qsiprep.tests.truth_scoring`), generated once per CI run
by the ``gen_trxscan_fixtures`` job from the pinned :data:`TRXSCAN_VERSION` and cached on the
checksum of ``.circleci/trxscan_fixtures.txt``, which :func:`main` writes from this file::

    python -m qsiprep.tests.trxscan_fixtures --spec > .circleci/trxscan_fixtures.txt
    python -m qsiprep.tests.trxscan_fixtures --generate /tmp/data/trxscan

Locally, :func:`fixture_dir` generates a missing fixture on demand when ``trxscan-fixture`` is
on PATH (``pip install "trxscan[trx]==<TRXSCAN_VERSION>"``; the ``trx`` extra reads the
phantom tractograms).

Fixtures are 3 mm, 16 directions + 2 b=0 per phase-encode polarity, from the hosted
``sub-60501`` phantom (400k streamlines), with the subject's T1w/T2w. Readout follows the
matrix (56 ms); susceptibility distortion rms 4.6 mm. Every DWI is magnitude-only.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

#: The TRXScan release the fixtures are generated with. Bumping it invalidates the CI cache.
TRXSCAN_VERSION = '0.2.0'

#: fixture name -> (recipe, {parameter: value}); values are JSON-encoded for ``--set``.
RECIPES = {
    # blip-up/blip-down pair: TOPUP / DRBUDDI reverse-series SDC, eddy, coregistration
    'rpe': ('rpe_series', {'voxel': 3, 'subject': 'rpe', 'noise': 1e-4}),
    # one series + a reverse-PE epi fieldmap under one B0FieldIdentifier
    'epi': ('epi_fieldmap', {'voxel': 3, 'subject': 'epi', 'noise': 1e-4}),
    # one series + a synthetic dual-echo GRE phasediff fieldmap; the T1w and the fieldmap were
    # acquired after the subject moved (recorded truth transforms), so fmap->b0 and b0->T1w
    # registration are scored against a real movement
    'phasediff': (
        'phasediff_fieldmap',
        {
            'voxel': 3,
            'subject': 'pdiff',
            'noise': 1e-4,
            'anat_offset': [3, -4, 2, 5, -3, 4],
            'fmap_offset': [-2, 3, 1, -4, 2, 3],
        },
    ),
    # strong gradient nonlinearity (synthetic Connectom coefficients x3: 3 deg median gradient
    # deviation, 2.5 mm median warp); the coefficient file is in the derivatives
    'gnl': (
        'rpe_series',
        {'voxel': 3, 'subject': 'gnl', 'noise': 1e-4, 'gnl': 'connectom-300', 'gnl_scale': 3},
    ),
    # the subject's measured head motion trace scaled x5 (5 mm / 2.8 deg range); the per-volume
    # poses are recorded in the derivatives
    'motion': ('motion', {'voxel': 3, 'subject': 'motion', 'noise': 1e-4, 'mb': 1, 'scale': 5}),
    # one series, no fieldmap, the subject's T2w: DIFFPREP's T2Wreg EPI correction
    't2wreg': ('rpe_series', {'voxel': 3, 'subject': 't2wreg', 'noise': 1e-4, 'pe': ['AP']}),
    # subject moved between the T1w and the DWI, and again between the AP and PA series
    'offsets': (
        'rpe_series',
        {
            'voxel': 3,
            'subject': 'rpeoff',
            'noise': 1e-4,
            'anat_offset': [3, -4, 2, 5, -3, 4],
            'pa_offset': [2, -3, 1, -3, 4, 2],
        },
    ),
}


def recipe_args(name):
    """Build the ``trxscan-fixture`` arguments for fixture ``name`` (without ``--out``)."""
    import json

    recipe, params = RECIPES[name]
    args = [recipe]
    for k, v in params.items():
        args += ['--set', f'{k}={json.dumps(v)}']
    return args


def spec_text():
    """Build the cache-key text: TRXScan version and every recipe's exact arguments."""
    lines = [
        '# generated by python -m qsiprep.tests.trxscan_fixtures --spec; do not edit',
        f'TRXSCAN_VERSION={TRXSCAN_VERSION}',
    ]
    for name in RECIPES:
        lines.append(f'{name}: ' + ' '.join(recipe_args(name)))
    return '\n'.join(lines) + '\n'


def generate(name, data_dir, exe='trxscan-fixture'):
    """Generate fixture ``name`` under ``<data_dir>/trxscan/<name>`` with ``trxscan-fixture``."""
    out = Path(data_dir) / 'trxscan' / name
    out.parent.mkdir(parents=True, exist_ok=True)
    cmd = [exe, *recipe_args(name), '--out', str(out)]
    subprocess.run(cmd, check=True)
    return out


def fixture_dir(name, data_dir=None):
    """Return the fixture's BIDS root, generating it when missing if ``trxscan-fixture`` exists."""
    if name not in RECIPES:
        raise ValueError(f'unknown TRXScan fixture {name!r}; known: {sorted(RECIPES)}')
    if not data_dir:
        from .utils import get_test_data_path

        data_dir = os.path.join(os.path.dirname(get_test_data_path()), 'test_data')
    out = Path(data_dir) / 'trxscan' / name
    if (out / 'dataset_description.json').exists():
        return out
    exe = shutil.which('trxscan-fixture')
    if exe is None:
        raise FileNotFoundError(
            f'TRXScan fixture {name!r} is not in {out.parent} and trxscan-fixture is not on PATH '
            f'(pip install "trxscan[trx]=={TRXSCAN_VERSION}", or run '
            f'python -m qsiprep.tests.trxscan_fixtures --generate {data_dir})'
        )
    return generate(name, data_dir, exe)


def main(argv=None):
    import argparse

    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--spec', action='store_true', help='print the cache-key spec text')
    ap.add_argument(
        '--generate', metavar='DATA_DIR', help='generate every fixture under DATA_DIR/trxscan'
    )
    ap.add_argument(
        '--only', nargs='*', default=None, help='restrict --generate to these fixture names'
    )
    a = ap.parse_args(argv)
    if a.spec:
        sys.stdout.write(spec_text())
        return 0
    if a.generate:
        for name in a.only or RECIPES:
            print(f'{name}: {generate(name, a.generate)}', flush=True)
        return 0
    ap.print_help()
    return 1


if __name__ == '__main__':
    sys.exit(main())
